import 'dotenv/config';
import path from 'node:path';

export const config = {
  port: Number(process.env.PORT || 8788),
  llmProvider: process.env.LLM_PROVIDER || 'ollama',
  ollamaBaseUrl: process.env.OLLAMA_BASE_URL || 'http://127.0.0.1:11434',
  ollamaModel: process.env.OLLAMA_MODEL || 'qwen3.5:0.8b',
  ollamaToolModel: process.env.OLLAMA_TOOL_MODEL || 'local-qwen35b-tools:latest',
  embeddingModel: process.env.EMBEDDING_MODEL || 'nomic-embed-text:latest',
  openaiBaseUrl: process.env.OPENAI_BASE_URL || '',
  openaiApiKey: process.env.OPENAI_API_KEY || '',
  openaiModel: process.env.OPENAI_MODEL || '',
  // 34B 本地工具模型首次装载通常超过 8 秒；请求级超时不应误判为模型失败。
  modelTimeoutMs: Number(process.env.MODEL_TIMEOUT_MS || 60_000),
  agentMaxSteps: Number(process.env.AGENT_MAX_STEPS || 4),
  toolTimeoutMs: Number(process.env.TOOL_TIMEOUT_MS || 5000),
  toolRetryCount: Number(process.env.TOOL_RETRY_COUNT || 1),
  webSearchProvider: process.env.WEB_SEARCH_PROVIDER || 'searxng',
  searxngBaseUrl: process.env.SEARXNG_BASE_URL || 'http://127.0.0.1:8081',
  webSearchTimeoutMs: Number(process.env.WEB_SEARCH_TIMEOUT_MS || 10_000),
  sandboxBaseUrl: process.env.SANDBOX_BASE_URL || 'http://127.0.0.1:8790',
  sandboxRunnerToken: process.env.SANDBOX_RUNNER_TOKEN || '',
  sandboxTimeoutMs: Number(process.env.SANDBOX_TIMEOUT_MS || 3_000),
  artifactDir: process.env.ARTIFACT_DIR || path.resolve(process.cwd(), 'artifacts'),
  artifactLinkTtlSeconds: Number(process.env.ARTIFACT_LINK_TTL_SECONDS || 900),
  traceRetention: Number(process.env.TRACE_RETENTION || 200),
  databaseUrl: process.env.DATABASE_URL || '',
  redisUrl: process.env.REDIS_URL || 'redis://127.0.0.1:6379',
  redisKeyPrefix: process.env.REDIS_KEY_PREFIX || 'agent-workbench:',
  minioEndpoint: process.env.MINIO_ENDPOINT || 'http://127.0.0.1:9000',
  minioAccessKey: process.env.MINIO_ACCESS_KEY || 'agent-minio',
  minioSecretKey: process.env.MINIO_SECRET_KEY || 'agent-minio-password',
  minioBucket: process.env.MINIO_BUCKET || 'agent-knowledge',
  jwtSecret: process.env.JWT_SECRET || 'replace-this-demo-secret-before-production',
  accessTokenTtl: process.env.ACCESS_TOKEN_TTL || '30m',
  refreshTokenTtlDays: Number(process.env.REFRESH_TOKEN_TTL_DAYS || 14),
  enableDemoLogin: process.env.ENABLE_DEMO_LOGIN !== 'false',
  demoUserEmail: process.env.DEMO_USER_EMAIL || 'demo@agent-workbench.local',
  demoUserPassword: process.env.DEMO_USER_PASSWORD || 'Demo123456!',
};
